# Site settings
title: ""
description: Welcome to my page as part of the Weizmann basic programming skills (Python) 2024.11 taught by [Gábor Szabó]("https://szabgab.com/")
baseurl: "" # Leave blank if deploying to the root (e.g., username.github.io), otherwise specify subpath (e.g., /project-name)
url: "https://github.com/O-BN" # Your GitHub Pages URL

# Author settings
author:""
  name: "osher Ben-Nun"
  email: "Osher.ben-nun@weizmann.ac.il"
# Theme settings
theme: minima # Replace with your chosen Jekyll theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Build settings
markdown: kramdown
highlighter: rouge
