title: Osher Ben-Nun
description: Welcome to my page as part of the Weizmann basic programming skills (Python) 2024.11 taught by [Gábor Szabó](https://szabgab.com/)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/O-BN" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Osher Ben-Nun
author-image:   ![]/(/pictures/my-pic)
author-job:     PhD student
author-email:   Osher.Ben-Nun@weizmann.ac.il # Add your email for contant form.
about-author:   I'm a PhD student from Jakub (Kobi) [Abramson's lab](https://www.weizmann.ac.il/dept/irb/abramson/).

# Social settings
social-github:    "https://github.com/O-BN"
social-linkedin: "https://www.linkedin.com/in/osher-ben-nun-a9a9b913b/"

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
