# Site settings
title: Your Site Title
description: A brief description of your site
baseurl: "" # Leave blank if deploying to the root (e.g., username.github.io), otherwise specify subpath (e.g., /project-name)
url: "https://username.github.io" # Your GitHub Pages URL

# Author settings
author:
  name: Your Name
  email: your.email@example.com

# Theme settings
theme: minima # Replace with your chosen Jekyll theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge
